FROM tensorflow/tensorflow:1.15.5-py3

WORKDIR /workspace
ENV PYTHONPATH /workspace

RUN apt-get update
RUN apt-get install -y \
    vim \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6

# install python package from requirements.txt
COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

RUN apt-get autoremove -y

CMD ["/bin/bash"]
